name: Build android common kernel spidev module

on:
  push:
    branches: [ "android12-5.10-2022-04" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Remove Useless Package
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt -y autoremove --purge
        sudo apt -y autoclean
        sudo apt clean

    - name: Install Package For Build
      run: |
        sudo apt update && sudo apt install -y curl liblz4-1 libyaml-0-2 p7zip-full gcc g++ bison bc make git zip flex zipalign libssl-dev python3 gcc-aarch64-linux-gnu cpio

    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 20480
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Download Build Tools
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://gerrit.googlesource.com/git-repo
        mkdir android-kernel && cd android-kernel
        ../git-repo/repo init --depth=1 --u https://android.googlesource.com/kernel/manifest -b common-android12-5.10-2022-12
        ../git-repo/repo sync
        cd common
        git checkout --orphan android12-5.10-2022-04
        git rm -rf .
        git pull https://github.com/zzh-zzh-zzh/android_gki_kernel_5.10_common.git android12-5.10-2022-04

    - name: Build spidev.ko Module
      run: |
        cd $GITHUB_WORKSPACE/android-kernel
        export BUILD_CONFIG=common/build.config.gki.aarch64
        bash build/build.sh
        # Build spidev.ko
        make -C common O=../out/android12-5.10 M=drivers/spi modules

    - name: Upload spidev.ko Module
      uses: actions/upload-artifact@v3
      with:
        name: spidev.ko
        path: android-kernel/out/android12-5.10/drivers/spi/spidev.ko
